#!/bin/sh -e
exec 2>&1

# Remove stale pid
rm -f /var/run/spamd.pid

# http://www.patorjk.com/software/taag/#p=display&c=echo&f=Big&t=SpamAssassin
echo "   _____                                                      _       "
echo "  / ____|                         /\                         (_)      "
echo " | (___  _ __   __ _ _ __ ___    /  \   ___ ___  __ _ ___ ___ _ _ __  "
echo "  \___ \| '_ \ / _\` | '_ \` _ \  / /\ \ / __/ __|/ _\` / __/ __| | '_ \ "
echo "  ____) | |_) | (_| | | | | | |/ ____ \\__ \__ \ (_| \__ \__ \ | | | |"
echo " |_____/| .__/ \__,_|_| |_| |_/_/    \_\___/___/\__,_|___/___/_|_| |_|"
echo "        | |                                                           "
echo "        |_|                                                           "
echo

sa-update && echo "Updated SpamAssassin rules" || echo "SpamAssassin rules up-to-date"

if [ "$TRUSTED_NETWORKS" != "" ]; then
    echo "Applying TRUSTED_NETWORKS"
    echo "trusted_networks $TRUSTED_NETWORKS" >/etc/mail/spamassassin/trusted_networks.cf
else
    rm -f /etc/mail/spamassassin/trusted_networks.cf
fi

if [ "$INTERNAL_NETWORKS" != "" ]; then
    echo "Applying INTERNAL_NETWORKS"
    echo "internal_networks $INTERNAL_NETWORKS" >>/etc/mail/spamassassin/internal_networks.cf
else
    rm -f /etc/mail/spamassassin/internal_networks.cf
fi

if [ "$DNS_CHECKS" = "true" ] || [ "$DNS_CHECKS" = "1" ]; then
    rm -f /etc/mail/spamassassin/rdns.cf
    exec spamd --ip-address --allowed-ips 0.0.0.0/0 --allowed-ips [::]/0 -u nobody -g nogroup --syslog stderr --nouser-config --pidfile /var/run/spamd.pid
else
    echo "score RDNS_NONE 0" >/etc/mail/spamassassin/rdns.cf
    exec spamd --local --ip-address --allowed-ips 0.0.0.0/0 --allowed-ips [::]/0 -u nobody -g nogroup --syslog stderr --nouser-config --pidfile /var/run/spamd.pid
fi
